CREATE TABLE lokomotiv_presets
(
	date_created timestamp default current_timestamp not null, 
    id int not null unique auto_increment,
	pkey varchar(120) not null, 
    pname varchar(120) primary key not null,
    bpm_sync float(7,6) unsigned not null,
    lfo_type_select decimal(7,6) unsigned not null,
    lfo_speed float(7,6) unsigned not null,
    lfo_target_select decimal(7,6) unsigned not null,
	lfo_amount float(7,6) unsigned not null,
    osc_hardsync_amount float(7,6) unsigned not null,
    osc_pw_amount float(7,6) unsigned not null,
    osc_saw_detune_amount float(7,6) unsigned not null,
	sub_osc_waveform  float(7,6) unsigned not null,
    osc_noise_amount float(7,6) unsigned not null,
    osc_saw_amount float(7,6) unsigned not null,
    osc_pulse_amount float(7,6) unsigned not null,
	sub_osc_amount float(7,6) unsigned not null,
    env_attack float(7,6) unsigned not null,
    env_decay float(7,6) unsigned not null,
    env_sustain float(7,6) unsigned not null,
	env_release float(7,6) unsigned not null,
	phonic_type  decimal(7,6) unsigned not null,
    filter_type_select decimal(7,6) unsigned not null,
    cutoff_amount float(7,6) unsigned not null,
    resonance_amount float(7,6) unsigned not null,
	kb_tracking_amount float(7,6) unsigned not null,
    envelope_amount float(7,6) unsigned not null,
    drive_pre_post_switch float(7,6) unsigned not null,
    drive_amount float(7,6) unsigned not null,
	amp_env_gate_select float(7,6) unsigned not null,
    amp_volume float(7,6) unsigned not null,
    pitch_bend_range decimal(8,6) unsigned not null,
    mod_wheel_target_select decimal(7,6) unsigned not null,
    velocity_target_select decimal(7,6) unsigned not null,
    portamento_speed float(7,6) unsigned not null
)